version: "2"
checks:
    return-statements:
      enabled: false
    method-complexity:
      config:
        threshold: 10
plugins:
  phpcodesniffer:
    enabled: true
    checks:
      PSR2 Methods MethodDeclaration Underscore:
        enabled: false
      PSR2 Classes PropertyDeclaration Underscore:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BreakNotNewLine:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BodyOnNextLineCASE:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCasePropertyName:
        enabled: false
  phan:
    enabled: true
    config:
      file_extensions: "php"