version: "2"
exclude_patterns:
  - "references/"
  - "vendor"
  - "*.yml"
checks:
    return-statements:
      enabled: false
    method-complexity:
      config:
        threshold: 15
    file-lines:
      config:
        threshold: 300

plugins:
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineLength TooLong:
        enabled: false
      Generic NamingConventions UpperCaseConstantName ClassConstantNotUpperCase:
        enabled: false
      Generic ControlStructures InlineControlStructure NotAllowed:
        enabled: false
      Generic Formatting DisallowMultipleStatements SameLine:
        enabled: false
      Generic Files LineEndings InvalidEOLChar:
        enabled: false
      PSR2 Methods MethodDeclaration Underscore:
        enabled: false
      PSR2 Classes PropertyDeclaration Underscore:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BreakNotNewLine:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BodyOnNextLineCASE:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BodyOnNextLineDEFAULT:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BreakIndent:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration TerminatingComment:
        enabled: false
      PSR2 Namespaces UseDeclaration MultipleDeclarations:
        enabled: false
      Squiz WhiteSpace ScopeClosingBrace ContentBefore:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration ContentAfterBrace:
        enabled: false
  phpmd:
    enabled: false
    checks:
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
  phan:
    enabled: true
    config:
      file_extensions: "php"
      # dead-code-detection: false
    checks:
        PhanUndeclaredMethod:
          enabled: false
        PhanUndeclaredProperty:
          enabled: false
        PhanUndeclaredConstant:
          enabled: false