version: "2"
exclude_patterns:
  - "references/"
  - "vendor"
  - "*.yml"
checks:
    return-statements:
      enabled: false
    method-complexity:
      config:
        threshold: 15
plugins:
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineLength TooLong:
        enabled: false
      Generic NamingConventions UpperCaseConstantName ClassConstantNotUpperCase:
        enabled: false
      Generic ControlStructures InlineControlStructure NotAllowed:
        enabled: false
      Generic Formatting DisallowMultipleStatements SameLine:
        enabled: false
      PSR2 Methods MethodDeclaration Underscore:
        enabled: false
      PSR2 Classes PropertyDeclaration Underscore:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BreakNotNewLine:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BodyOnNextLineCASE:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BodyOnNextLineDEFAULT:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BreakIndent:
        enabled: false
      Squiz WhiteSpace ScopeClosingBrace ContentBefore:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration ContentAfterBrace:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCasePropertyName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
  phan:
    enabled: true
    config:
      file_extensions: "php"